modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-modifiedbiomesource/issues"
license = "ARR"

[[mods]]
modId = "modifiedbiomesource"
version = "${version}"
displayName = "Modified Biome Source"
authors = "mahmudindev"
description = '''
Add modified biome sources that can be configured.
'''
logoFile = "assets/modifiedbiomesource/icon.png"

[[dependencies.modifiedbiomesource]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modifiedbiomesource]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "modifiedbiomesource.mixins.json"
